  db:
      - 
        name: db_opensea
        type: postgres
        host: localhost
        port: 5432
        username: postgres
        password: 123456
        database: opensea
        synchronize: true
        logging: false
        entities: [dist/entity/db_opensea/*.js]
  redis: 
      - 
        host: 127.0.0.1
        port: 6379
        password: 
        db: 1